// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCir07MdH0Fg2w3K8ueRw9O5M5u5YIugyU',
    appId: '1:828340040997:web:e321d57e7b6427fb0756cc',
    messagingSenderId: '828340040997',
    projectId: 'first-7eb96',
    authDomain: 'first-7eb96.firebaseapp.com',
    storageBucket: 'first-7eb96.appspot.com',
    measurementId: 'G-YQ7ZH3GH4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5uSdIbBsbe5pXKd37ELOZdTrkulg6mF0',
    appId: '1:828340040997:android:b6cf6a8d9108544e0756cc',
    messagingSenderId: '828340040997',
    projectId: 'first-7eb96',
    storageBucket: 'first-7eb96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByL4QDAplPS-vCXZn_Fb1Y1xnWkDs9R14',
    appId: '1:828340040997:ios:6878644745ef97790756cc',
    messagingSenderId: '828340040997',
    projectId: 'first-7eb96',
    storageBucket: 'first-7eb96.appspot.com',
    iosBundleId: 'com.example.f3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByL4QDAplPS-vCXZn_Fb1Y1xnWkDs9R14',
    appId: '1:828340040997:ios:76648c366711d6920756cc',
    messagingSenderId: '828340040997',
    projectId: 'first-7eb96',
    storageBucket: 'first-7eb96.appspot.com',
    iosBundleId: 'com.example.f3.RunnerTests',
  );
}
